# Generated by Django 4.0.10 on 2023-05-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='chassi',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='em_servico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='placa',
            field=models.CharField(default='0', max_length=14),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='0', max_length=14),
        ),
    ]
