# Generated by Django 4.0.10 on 2023-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0003_cliente_chassi_cliente_em_servico_cliente_placa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='oficina',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='cliente',
            name='servico',
            field=models.CharField(default='', max_length=150),
        ),
    ]
