# Generated by Django 4.0.10 on 2023-05-29 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0005_cliente_data_encerramento_cliente_data_incio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_encerramento',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor_pecas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor_servico',
            field=models.IntegerField(default=0),
        ),
    ]
