# Generated by Django 4.0.10 on 2023-05-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0007_login_chave_login_oficina_alter_login_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='chave',
            field=models.IntegerField(default=0),
        ),
    ]
