# Generated by Django 4.0.10 on 2023-05-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0009_alter_cliente_valor_pecas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(max_length=100)),
                ('chave', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
